// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceContext } from "./InterfaceContext";

/**
 * Network context snapshot. Used both as the PUT /network/context request
 * body and as the `context` field in the GET /network/context response.
 *
 * Field names are snake_case on the wire in both directions, matching
 * mihomo's JSON contract. Note: the GET response's `context` is a
 * normalized snapshot and does NOT echo back the TTL, so a value read from
 * GET cannot be pushed straight into a PUT while preserving "expiring vs
 * sticky" semantics — callers that need to replay must set `ttl`
 * explicitly themselves.
 */
export type NetworkContext = { version: number, interfaces: Array<InterfaceContext>, dns_suffix?: Array<string>, ttl?: number, };
