name: Build dist js

on:
  push:
    branches:
      - main
    paths:
      - "guest-js/**"
      - "src/models.rs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Export Bindings
        run: cargo test export_bindings

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true

      - name: build dist
        run: pnpm build

      - name: upload dist-js
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Update dist"
          git push origin main
