name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: install webkit2gtk
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: |
          cargo clippy --workspace --all-targets --all-features -- -D warnings
